/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freecell.view;

import br.edu.uesb.aed.freecell.model.Baralho;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;

/**
 *
 * @author matheus
 */
public class FrameMudarDePilha extends javax.swing.JFrame {

    /**
     * Creates new form FrameMudarDePilha
     */
    ButtonGroup buttons = new ButtonGroup();
    
    
    
    public FrameMudarDePilha() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bEspaco1 = new javax.swing.JToggleButton();
        bEspaco2 = new javax.swing.JToggleButton();
        bEspaco3 = new javax.swing.JToggleButton();
        bEspaco4 = new javax.swing.JToggleButton();
        bPilhaBase = new javax.swing.JToggleButton();
        bPilha1 = new javax.swing.JToggleButton();
        bPilha2 = new javax.swing.JToggleButton();
        bPilha3 = new javax.swing.JToggleButton();
        bPilha4 = new javax.swing.JToggleButton();
        bPilha5 = new javax.swing.JToggleButton();
        bPilha6 = new javax.swing.JToggleButton();
        bPilha7 = new javax.swing.JToggleButton();
        bPilha8 = new javax.swing.JToggleButton();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Para onde deseja mover a carta?");

        bEspaco1.setText("Espaço 1");
        buttons.add(bEspaco1);

        buttons.add(bEspaco2);
        bEspaco2.setText("Espaço 2");

        buttons.add(bEspaco3);
        bEspaco3.setText("Espaço 3");

        buttons.add(bEspaco4);
        bEspaco4.setText("Espaço 4");

        buttons.add(bPilhaBase);
        bPilhaBase.setText("Pilha Base");

        buttons.add(bPilha1);
        bPilha1.setText("Pilha 1");

        buttons.add(bPilha2);
        bPilha2.setText("PIlha 2");

        buttons.add(bPilha3);
        bPilha3.setText("Pilha 3");

        buttons.add(bPilha4);
        bPilha4.setText("Pilha 4");

        buttons.add(bPilha5);
        bPilha5.setText("Pilha 5");

        buttons.add(bPilha6);
        bPilha6.setText("Pilha 6");

        buttons.add(bPilha7);
        bPilha7.setText("Pilha 7");

        buttons.add(bPilha8);
        bPilha8.setText("Pilha 8");

        bOk.setText("OK");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });

        bCancelar.setText("CANCELAR");

        javax.swing.GroupLayout JPanelFundoLayout = new javax.swing.GroupLayout(JPanelFundo);
        JPanelFundo.setLayout(JPanelFundoLayout);
        JPanelFundoLayout.setHorizontalGroup(
            JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelFundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JPanelFundoLayout.createSequentialGroup()
                        .addComponent(bPilha1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPilha2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPilha3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPilha4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanelFundoLayout.createSequentialGroup()
                        .addGroup(JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelFundoLayout.createSequentialGroup()
                                .addComponent(bEspaco1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEspaco2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEspaco3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEspaco4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelFundoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bOk, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JPanelFundoLayout.createSequentialGroup()
                                    .addComponent(bPilha5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bPilha6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bPilha7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bPilha8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bPilhaBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JPanelFundoLayout.setVerticalGroup(
            JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEspaco1)
                    .addComponent(bEspaco2)
                    .addComponent(bEspaco3)
                    .addComponent(bEspaco4)
                    .addComponent(bPilhaBase))
                .addGap(39, 39, 39)
                .addGroup(JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPilha1)
                    .addComponent(bPilha2)
                    .addComponent(bPilha3)
                    .addComponent(bPilha4)
                    .addComponent(bPilha5)
                    .addComponent(bPilha6)
                    .addComponent(bPilha7)
                    .addComponent(bPilha8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(JPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        AcaoDoSelecionado();
        this.dispose();
    }//GEN-LAST:event_bOkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelFundo;
    private javax.swing.JButton bCancelar;
    private javax.swing.JToggleButton bEspaco1;
    private javax.swing.JToggleButton bEspaco2;
    private javax.swing.JToggleButton bEspaco3;
    private javax.swing.JToggleButton bEspaco4;
    private javax.swing.JButton bOk;
    private javax.swing.JToggleButton bPilha1;
    private javax.swing.JToggleButton bPilha2;
    private javax.swing.JToggleButton bPilha3;
    private javax.swing.JToggleButton bPilha4;
    private javax.swing.JToggleButton bPilha5;
    private javax.swing.JToggleButton bPilha6;
    private javax.swing.JToggleButton bPilha7;
    private javax.swing.JToggleButton bPilha8;
    private javax.swing.JToggleButton bPilhaBase;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void AcaoDoSelecionado() {//acão do botão selecionado do grupo

        ButtonModel m = buttons.getSelection();

        if (m.equals(bEspaco1.getModel())) {
            System.out.print("teste");//teste
        } else if (m.equals(bEspaco2.getModel())) {

        } else if (m.equals(bEspaco3.getModel())) {

        } else if (m.equals(bEspaco4.getModel())) {

        } else if (m.equals(bPilha1.getModel())) {

        } else if (m.equals(bPilha2.getModel())) {

        } else if (m.equals(bPilha3.getModel())) {

        } else if (m.equals(bPilha4.getModel())) {

        } else if (m.equals(bPilha5.getModel())) {

        } else if (m.equals(bPilha6.getModel())) {

        } else if (m.equals(bPilha7.getModel())) {

        } else if (m.equals(bPilha8.getModel())) {

        } else if (m.equals(bPilhaBase.getModel())) {

        }
//    public void actionPerformed(java.awt.event.ActionEvent evt) {
//        evt.getActionCommand();
//    }
    }

}
